name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r26d

      - name: Build
        working-directory: AndUEDumper
        env:
          NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}
        run: |
          make clean
          make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UEDump3r-builds
          path: |
            AndUEDumper/libs/**
            AndUEDumper/bin/**
            AndUEDumper/obj/**/*.so
          if-no-files-found: warn
