name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build unzip wget

      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip android-ndk-r21e-linux-x86_64.zip
          mv android-ndk-r21e $HOME/android-ndk
          echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV
          echo "$HOME/android-ndk" >> $GITHUB_PATH

      - name: Build native for all ABIs
        run: |
          ABIs=("arm64-v8a" "armeabi-v7a" "x86" "x86_64")
          for ABI in "${ABIs[@]}"; do
              mkdir -p build/$ABI
              cmake -S . -B build/$ABI -G Ninja \
                  -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
                  -DANDROID_ABI=$ABI \
                  -DANDROID_NATIVE_API_LEVEL=21 \
                  -DCMAKE_BUILD_TYPE=Release
              cmake --build build/$ABI --config Release -j$(nproc)
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UE4Dumper
          path: build/
