name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build project with Gradle
        run: ./gradlew :module:assembleRelease

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UE4Dumper
          path: out/magisk_module_release/
